---
layout: post
title: "Why the Uncoast Unconf?"
date: "2019-01-07 12:00:00 CST"
categories: blog, unconf, midwest
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Announcing the [Uncoast Unconference](https://uncoast-unconference.netlify.com/)!

I'm very excited to announce this event, which we have been working on for several months and thinking about for *years*. The Uncoast Unconf (#uncoastUnconf), to be held April 14-16, 2019, in Des Moines, IA, is for R users and developers living off-coast in the US to come together for collaboration and community building. For more information about the event, please visit our [website](https://uncoast-unconference.netlify.com/). For some insight into why this event has come to be, please read on! 

## Travel Costs

In 2017 and 2018, I was lucky enough to attend the [ROpenSci](http://unconf18.ropensci.org/) [Unconfs](http://unconf17.ropensci.org/). I met a lot of amazing people, and had a great time collaborating with some amazing R-Ladies and fellow ROpen Sci Fellows. I also got to meet a lot of folks in person that I had only ever interacted with on Twitter. I loved attending these events! There was, however, one problem: I was coming from Des Moines, Iowa, to Los Angeles or Seattle, and those are not cheap or quick trips! 

## Building a Midwest R community

Another thing I noticed at theses events was that most of the other attendees were from places very far away from me in Iowa. This is great for broadening horizons and for learning about the many ways that people use R all over the country and world. However, it's less great for fostering continuing collaboration and interaction within a community that is spread out across the world's timezones. I also felt a distinctly coastal bent in the events, because that's where they were held, where most of the attendees were from, and where much focus in the larger R and tech communities seems to be. But because I am at Iowa State University, I know that there are many amazing R users in "flyover country." (And yes, I am reclaiming this usually pejorative term on behalf of all midwesterners, especially those lifelong ones like myself!) 

## A space for YOU!

It's not hard to find great R users and developers off the coasts. Just look at my fellow members of the Uncoast Unconf organizing committee: someone who's used R in data science at John Deere, someone who's used R working at a nuclear power plant in Nebraska, my advisor and an eminent statistical graphics researcher who is always learning new R things (not something that can be said for many tenured professors), one of the most passionate R users I've ever met, and an R Spatial Advocate at UChicago, which is definitely one of the cooler job titles out there. 

I figured that if these are just some of the people I'm aware of, there must be so many more amazing R users and developers out here! So this conference is for you, fellow uncoasters. If you use R at school, in your government job, in your industry job, or as an academic, and you are looking for a way to meet and build relationships with other R users like you, please [apply](https://iastate.qualtrics.com/jfe/form/SV_b45oWxx4lIt8NMh) to attend! (Spots will be limited.) Des Moines is (probably) much cheaper to get to than Los Angeles or Seattle or New York, and it's hopefully driveable for some of you as well. (Looking at you, Kansas Citians and Twin Citians!) Please spread the word, and reach out to me on Twitter if you have any questions!

## With much gratitude

This would not have happened without support, organization, and encouragement from several amazing members of the R community. Thank you. 

#### Thanks to the organizing committee:

- Sam Helmich
- Susan Vanderplas
- Heike Hofmann 
- [Ian Lyttle](http://ijlyttle.github.io/)
- Angela Li (check out her [event](https://chirunconf.github.io/) in March if you're in the Chicago area!)


#### Thank you to the following people for their additional support! 

- [Stef Butland](https://twitter.com/stefaniebutland?lang=en), for chats and emails and helping me get the idea off the ground.
- [Nick Tierney](https://www.njtierney.com/), for logistical guidance and for providing some materials from the [Oz Unconfs](https://ozunconf18.ropensci.org/).
- Alicia Carriquiry, for her support and encouragement, as well as the account infrastructure for taking in and spending funds. 
- [Yihui Xie](https://yihui.name/en/), for his enthusiastic "Yes!" when we asked him to attend.

### If you or your employer are interested in sponsoring this event, please [reach out](mailto:sctyner@iastate.edu)! 
