---
layout: post
title: "A Post I Didn't Want to Write"
date: "2019-10-26  00:00:00 CDT"
categories: rstats, community
---

This post is about DataCamp (DC). I wrote two projects for DC before I learned of the incident of sexual harassment by someone high up in the company. It has since been revealed that it was the CEO, Jonathan Cornelissen (JC). Many people have written about this incident and the company's response (or lack of response). Here is a non-exhaustive list:

- [Buzzfeed](https://www.buzzfeednews.com/article/daveyalba/datacamp-sexual-harassment-metoo-tech-startup)
- [Noam Ross 1](https://www.noamross.net/2019/04/12/datacamp-sexual-assault/)
- [Noam Ross 2](https://www.noamross.net/2019/04/30/questions-for-datacamp/)
- [R-Ladies Global Team 1](https://blog.rladies.org/post/statement-about-datacamp/)
- [R-Ladies Global Team 2](https://blog.rladies.org/post/datacamp-third-party-review/)
- [RStudio](https://twitter.com/rstudio/status/1117889763711696896)
- [Anaconda](https://www.anaconda.com/updated-statement-about-our-relationship-with-datacamp/)
- [Heather Nolis](https://medium.com/@heathernolis/on-datacamp-aafd82f94e60)


## Why I didn't want to write this

I still think DC is a really great platform to learn programming languages. I used it frequently, and I recommended it to others. When I got the opportunity to work with DC, I was excited to be contributing to and financially gaining from something I loved to use. I even set up weekly meetings with other folks in my office so that we could use DC for professional development time.  

When I learned of the harassment, I was gutted.  I had trusted this company, benefitted from this company professionally and financially, and put my photo, name, and intellectual property on their website. This harassment showed me that I was wrong to trust them. So why am I just writing this now? 

FIrst, I was one of many signees on a letter by external DC content creators urging DC to go public with the harassment and take appropriate action. The day after it was sent to DC, they published the [initial post](https://www.datacamp.com/community/blog/note-to-our-community) revealing the incident to the public and explaining some steps they would take, including getting an independent entity to review the company's handling of the incident. I thought these steps sounded promising. This was in April. 

In June, I applied to be on their instructor advisory board (IAB). (You can see the application questions and my answers at the end of this post). I interviewed with three people: Martin Theuwissen (audio only), Sue Lai (audio and video), and Mari Navary (audio and video). Though I ultimately wasn't chosen, I thought my conversations went well, they seemed receptive to my feedback (Sue even thanked me for my advocacy), and I was encouraged by the names I saw on the board. Again, I thought it sounded promising and was a step in the right direction. 

Then, they posted [this statement](https://www.datacamp.com/community/blog/working-ideal-independent-third-party-review-of-datacamp) about the third-party review. The stated author of the post is the interim CEO, who I spoke with for my IAB interview. The post quotes from the [full report](https://assets.datacamp.com/working-ideal-independent-third-party-review-of-datacamp.pdf)

## Are we asking too much of DC? 

Get rid of their co-founder and CEO and chief board member? Doesn't that seem like overkill? All he did was dance, right? You're seriously gonna take away everything he's built for a dance?? Here's what I think about that: 

1. He is just one person. He didn't build DC on his own, as is evidenced by the 2 other co-founders, approximately 90 employees, and at least 100 external instructors. [(DataCamp's profile on Pitchbook.)](https://pitchbook.com/profiles/company/83549-98) In fact, without some high-profile external instructors, DataCamp would likely not have been as successful. Those high-profile folks lent their reputations to DataCamp and helped legitimize them as a company, not the other way around. 
2. The "dancing" incident was not just dancing. It did not occur in a room full of independent individuals who were totally unaffiliated with each other and who just happened to choose the same place to go out to that night. In that situation, say a night out with a few friends at a club, everyone is basically equal. There are no power dynamics at play. In a situation like that, where no one knew who he (JC) was and noone else worked at DC, I would agree that it was "just dancing." However. That was NOT the situation. The "dancing" was at an event by and for DC employees. In that room, everyone knew he was the CEO of DC. He knew that everyone who was there worked for him. In contrast with the night-out-at-the-club scenario, he was in a position of power over everyone. He knew that. *And yet, he still chose to put his hands on his employee.* It's that simple. The fact that JC and other DC board members refuse to see and understand that proves that JC should be permanently removed from any affiliation with DC. I don't care that everyone was drinking and I don't care what his intentions were. The bottom line is: good leaders conduct themselves in a manner that shows they understand the power dynamics at play and they don't get drunk (past the point of being able to remember things [quote report]) in a room full of their employees. They know their limits. JC clearly didn't. Being a CEO comes with a lot of perks (wealth, power, fame, etc.), but those perks come with serious responsibilities that JC ignored. 
3. As the WorkingIdeal report states, DC has "a young leadership team with little or no direct management experience." In addition, a the time, "Management did not have the policies or practices in place to handle workplace harassment and related concerns (and several employees shared that they did not know the process to report harassment despite having signed a sexual harassment policy)." (p. 4)

---

My other thoughts: (notes)

Company response was slow, ineffective, insensitive, unfeeling

- Collective shrug over inappropriate behavior of CEO
- They could have dealt with it directly from the beginning
- Clearly a symptom of a larger cultural problem. 

CEO online temper tantrum proves the environment at DataCamp is not healthy. He clearly does not have the temperament of a true leader.

- clearly interested in using his professional power for personal gain 
- Good leaders understand the power imbalance between themselves and their employees and don’t do anything to take advantage of that. 
- Liking tweets, proving he’s unwilling to grow, change, accept responsibility for his actions. 
The fact that they are unwilling to let go of him permanently demonstrates that they are more concerned with their c suite than their employees, instructors, and users. 

Embarrassed to be associated with the company 

- Will not be creating new content for them and I will donate all royalties to the Times Up foundation 
- Make my content available on my personal github 
- Will not be recommending DataCamp to anyone anymore. 

Programming as a whole has a very bad reputation for being exclusive, unwelcoming and anti-women. The fact that DC fails to see how this incident fits into a larger community pattern shows just how (willingly or not) tone-deaf they are. For a product that is supposed to welcome newcomers into programming, it certainly has not shown that it actually takes that mantle seriously or is willing to change. 


---

### My IAB Application

*Last edited June 12, 2019*

#### Q1: Please briefly describe your primary job functions.

Currently, I am a postdoctoral research associate in the Center for Statistics and Applications in Forensic Evidence at Iowa State University. In this role, I primarily perform tasks related to applied statistical research. These include: authoring original research papers, performing statistical analysis in R, constructing data visualizations in R, collaborating with colleagues using Git/Github, and professional education and outreach online and in person (e.g. attending conferences, webinars, workshops, etc). Other work includes organizing meetings & conferences and editing & co-authoring an online book, Open Forensic Science in R.

#### Q2: Why do you want to be on the IAB?

I want to serve on DataCamp’s IAB because I think that DataCamp provides an excellent data science learning platform, and I want to be a part of steering the organization in the right direction. Since the scandal surrounding the CEO has come to light, I have been deeply disappointed with some of the decisions that DataCamp leadership has made. However, I want the DataCamp platform to succeed: I believe it is an excellent tool for learning. I have really enjoyed creating projects for DataCamp and taking courses myself. Because I believe that DataCamp has some major flaws and it is an excellent online learning platform, I believe I have a duty as both a user and a content creator to make sure the company succeeds for the right reasons. 

Please describe a few areas and topics you think the IAB should focus on. *
The first priority should be recommending that the company takes appropriate actions after the review by Ms. Bhargava. The way DataCamp handled the 2017 assault incident was unequivocally wrong, and we as instructors need to be certain that the culture at DataCamp will change before we continue to have a relationship with DataCamp. The way the company handled the incident led to many in the data science community, including many DataCamp instructors, to completely lose trust in DataCamp. Rebuilding that trust is going to be incredibly difficult, and I think that the IAB should make this their only goal for the near future. Without the trust of the instructor community, DataCamp is sure to fail.

Once the instructor and data science communities have begun to trust DataCamp again, the IAB should also focus on making the process of becoming an instructor more transparent. This includes publishing things like preferred instructor qualifications, course development time requirements, and payment & royalties information. Making this information available will also help foster trust in DataCamp. 

The company should also provide a formal method for external instructors to directly communicate with each other, instead of relying on their own personal networks. The instructors should be able to speak openly with each other, and thus their communication should not be viewed by DataCamp employees. There also needs to be a formal mechanism in place for instructors to raise concerns with DataCamp leadership directly, and there needs to be an official process in place to quickly and effectively deal with instructors’ concerns. 

#### Q: Which data science groups or communities are you involved with? Please describe your involvement in that community. *

I am involved with the R-Ladies organization. I co-founded the R-Ladies Ames chapter, and I have given several talks and workshops as a part of that group. In addition, I am an rOpenSci fellow, and I have attended two of their unconferences, which inspired me to create my own unconference, the “Uncoast Unconf,” which was held in April of 2019 in Des Moines, IA. I am also active in the #rstats community on Twitter. 
